
POST http://127.0.0.1:8000/api/packages/ HTTP/1.1
content-type: application/json
#Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA4MDExNzI0LCJpYXQiOjE3MDc5MjUyNjQsImp0aSI6ImFlOTM1ZWFhOTBjNzQwOTU5NDUzY2JhMWVlOWMxNDA4IiwidXNlcl9pZCI6MX0.31KDSk1qnPqTu-MS2d9yV8Ju8fHAIPJkAtO5xB4mU_k
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA4MDExODI2LCJpYXQiOjE3MDc5MjUzNjYsImp0aSI6IjZmNmQ1MDE4N2M2ZTQwMmE5ODUyNjg2YzI2NDY3NjgzIiwidXNlcl9pZCI6Mn0.v-FFkvB9w7VtP0D3s9EylyOOqsKkC51tCvig3DHOpws

{
    
}

###

POST  http://127.0.0.1:8000/api/register HTTP/1.1
content-type: application/json

{
    "email": "user@gmail.com",
    "password": "user@1234"
}

###

POST  http://127.0.0.1:8000/api/login/user HTTP/1.1
content-type: application/json

{
    "email": "user@gmail.com",
    "password": "user@1234"
}

###

POST  http://127.0.0.1:8000/api/login/admin HTTP/1.1
content-type: application/json

{
    "email": "admin@admin.com",
    "password": "admin@123"
}

###

PUT  http://127.0.0.1:8000/api/profile HTTP/1.1
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA4MDExMzQwLCJpYXQiOjE3MDc5MjQ4ODAsImp0aSI6IjA5NDhmZDc5NzE4NzQ4YjE4YjJjNjQ2ZDkxMzJlMzFmIiwidXNlcl9pZCI6MX0.YzUeRvYdV2Q0pM4VgXRt93G9lyOgptoYE8o22Gb9Rok

{
  "first_name": "Admin",
  "last_name": "Admin",
  "phone_no": "1234567876",
  "address": "sdyfutaslbdfi",
  "detail":"/Users/amar/Desktop/practice/veryacademy/drf2/media/places/default.jpg"
}

###
# PUT  http://127.0.0.1:5000/package/update/cd5e37fe-b9f0-4337-bde9-f863bf56a584 HTTP/1.1
# content-type: application/json

# {
#     "packageDuration": 10
    
# }

# POST http://127.0.0.1:5000/package/add-image/cd5e37fe-b9f0-4337-bde9-f863bf56a584 HTTP/1.1
# content-type: application/json

# {
    
    
# }

# DELETE http://127.0.0.1:5000/package/delete-image/cd5e37fe-b9f0-4337-bde9-f863bf56a584/c0d525d2-315e-4a7b-a940-a71192e880aa HTTP/1.1
# content-type: application/json

# {
    
    
# }