# Generated by Django 4.2.10 on 2024-02-15 07:27

from django.db import migrations, models
import packages.models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0005_rename_available_slots_packages_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="places",
            name="Img",
            field=models.ImageField(
                upload_to=packages.models.profile_image_path, verbose_name="Image"
            ),
        ),
    ]
