# Generated by Django 4.2.10 on 2024-02-16 06:24

from django.db import migrations, models
import packages.models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0006_alter_places_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packages",
            name="days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="places",
            name="Img",
            field=models.ImageField(
                default="places/default.jpg",
                upload_to=packages.models.profile_image_path,
                verbose_name="Image",
            ),
        ),
    ]
